import React from 'react';

export type UnitSkills = {
    firstStrike: boolean,
    ranged: boolean,
    flanking: boolean,
    doubleStrike: boolean,
    trample: boolean,
    lastStrike: boolean,
}

export type UnitInfo = {
    name: string,
    friendly: boolean,
    maxHp: number,
    attack: number,
    crit: number,
    order: number,
    tier: number,
    skills: UnitSkills,
    unitImageURL: string,
    weaponImageURL: string,
}

export function isBoss(u: UnitInfo): boolean {
    return u.tier >= 25;
}

function skills(s?: Partial<UnitSkills>): UnitSkills {
    return Object.assign({
        firstStrike: false,
        ranged: false,
        flanking: false,
        doubleStrike: false,
        trample: false,
        lastStrike: false,
    }, s ?? {});
}

export const unitInfos: UnitInfo[] = [
    {
        name: "Militia",
        friendly: true,
        maxHp: 15,
        attack: 5,
        crit: 0.8,
        order: 0,
        tier: 1,
        skills: skills(),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/e/e7/Militia.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/1/1c/Pitchfork.png",
    },
    {
        name: "Archer",
        friendly: true,
        maxHp: 10,
        attack: 20,
        crit: 0.8,
        order: 5,
        tier: 1,
        skills: skills({ ranged: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/2/29/Archer.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/6/65/Bow.png",
    },
    {
        name: "Footsoldier",
        friendly: true,
        maxHp: 40,
        attack: 15,
        crit: 0.8,
        order: 1,
        tier: 1,
        skills: skills(),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/5/5e/Recruit.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/b/b9/Copper_sword.png",
    },
    {
        name: "Longbow Archer",
        friendly: true,
        maxHp: 10,
        attack: 15,
        crit: 0.8,
        order: 6,
        tier: 2,
        skills: skills({ ranged: true, doubleStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/e/ea/Longbow_archer.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/e/e4/Longbow.png",
    },
    {
        name: "Knight",
        friendly: true,
        maxHp: 90,
        attack: 20,
        crit: 0.8,
        order: 2,
        tier: 3,
        skills: skills(),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/6/6b/Knight.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/3/3c/Iron_sword.png",
    },
    {
        name: "Crossbowman",
        friendly: true,
        maxHp: 15,
        attack: 90,
        crit: 0.8,
        order: 7,
        tier: 3,
        skills: skills({ ranged: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/c5/Crossbow_archer.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/7/79/Crossbow.png",
    },
    {
        name: "Cavalry",
        friendly: true,
        maxHp: 5,
        attack: 5,
        crit: 0.8,
        order: 4,
        tier: 2,
        skills: skills({ flanking: true, firstStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/1/15/Cavalry.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/c3/Horse.png",
    },
    {
        name: "Cuirassier",
        friendly: true,
        maxHp: 120,
        attack: 10,
        crit: 0.8,
        order: 3,
        tier: 4,
        skills: skills({ firstStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/f/ff/Cuirassier.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/ce/Armored_horse.png",
    },
    {
        name: "Cannoneer",
        friendly: true,
        maxHp: 60,
        attack: 80,
        crit: 0.8,
        order: 8,
        tier: 4,
        skills: skills({ trample: true, lastStrike: true, ranged: true, flanking: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/cd/Cannonneer.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/a/a6/Cannon.png",
    },
    {
        name: "Orkling",
        friendly: false,
        maxHp: 15,
        attack: 5,
        crit: 0.6,
        order: 0,
        tier: 1,
        skills: skills(),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/1/14/Orc_1.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/5/50/Club.png",
    },
    {
        name: "Orc Hunter",
        friendly: false,
        maxHp: 10,
        attack: 20,
        crit: 0.6,
        order: 5,
        tier: 1,
        skills: skills({ ranged: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/1/14/Orc_1.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/6/65/Bow.png",
    },
    {
        name: "Orc Raiders",
        friendly: false,
        maxHp: 40,
        attack: 15,
        crit: 0.6,
        order: 1,
        tier: 1,
        skills: skills(),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/1/14/Orc_1.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/b/b9/Copper_sword.png",
    },
    {
        name: "Elite Orc Hunters",
        friendly: false,
        maxHp: 10,
        attack: 15,
        crit: 0.6,
        order: 6,
        tier: 2,
        skills: skills({ ranged: true, doubleStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/2/2d/Orc_2.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/e/e4/Longbow.png",
    },
    {
        name: "Orc Veteran",
        friendly: false,
        maxHp: 90,
        attack: 20,
        crit: 0.6,
        order: 2,
        tier: 3,
        skills: skills(),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/a/ab/Orc_3.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/3/3c/Iron_sword.png",
    },
    {
        name: "Elite Orc Sniper",
        friendly: false,
        maxHp: 15,
        attack: 90,
        crit: 0.6,
        order: 7,
        tier: 3,
        skills: skills({ ranged: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/a/ab/Orc_3.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/7/79/Crossbow.png",
    },
    {
        name: "Warg Rider",
        friendly: false,
        maxHp: 5,
        attack: 5,
        crit: 0.6,
        order: 4,
        tier: 2,
        skills: skills({ flanking: true, firstStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/2/2d/Orc_2.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/c3/Horse.png",
    },
    {
        name: "Orc Vanguard",
        friendly: false,
        maxHp: 120,
        attack: 10,
        crit: 0.6,
        order: 3,
        tier: 4,
        skills: skills({ firstStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/ce/Orc_4.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/ce/Armored_horse.png",
    },
    {
        name: "Orc Demolisher",
        friendly: false,
        maxHp: 60,
        attack: 80,
        crit: 0.6,
        order: 8,
        tier: 4,
        skills: skills({ ranged: true, trample: true, flanking: true, lastStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/c/ce/Orc_4.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/a/a6/Cannon.png",
    },
    {
        name: "Bula (boss 1)",
        friendly: false,
        maxHp: 5000,
        attack: 150,
        crit: 0.5,
        order: 100,
        tier: 100,
        skills: skills({ trample: true, lastStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/f/ff/Orc_boss_1.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/d/df/Wood.png",
    },
    {
        name: "Aguk (boss 2)",
        friendly: false,
        maxHp: 11000,
        attack: 300,
        crit: 0.5,
        order: 100,
        tier: 150,
        skills: skills({ trample: true, lastStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/a/a9/Orc_boss_2.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/b/b9/Copper_sword.png",
    },
    {
        name: "Mazoga (boss 3)",
        friendly: false,
        maxHp: 120000,
        attack: 100,
        crit: 0.5,
        order: 3.5,
        tier: 200,
        skills: skills({ trample: true, lastStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/b/b5/Orc_boss_3.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/3/3c/Iron_sword.png",
    },
    {
        name: "Durgash (boss 4)",
        friendly: false,
        maxHp: 40000,
        attack: 500,
        crit: 0.5,
        order: 100,
        tier: 300,
        skills: skills({ trample: true, firstStrike: true }),
        unitImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/9/9c/Orc_boss_4.png",
        weaponImageURL: "https://static.wikia.nocookie.net/paragonpioneers/images/a/a6/Cannon.png",
    },
];